simple_local_planner:
  output_frame: map
  local_path_length: 100
  nearest_neighbor_search: kd_tree  # kd_tree. ball_tree, brute, auto
  transform_timeout: 0.06
  dense_waypoint_interval: 0.1
  tfl_maximum_deceleration: 2.8
  braking_safety_distance_obstacle: 4.0
  braking_safety_distance_stopline: 2.0
  braking_safety_distance_goal: 0.0